### ISSUE TITLE
Double counting of Stripe fees in Net Sales calculation

### ISSUE THREAD

**Issue by manwithpowers** [rvola/woo-stripe-fee-in-report#2]
The plugin is currently double counting Stripe fees when calculating Net Sales for the chart sidebar:
`$this->report_data->net_sales = wc_format_decimal( $this->report_data->total_sales - $this->report_data->total_shipping - $this->report_data->total_stripe_fees - max( 0, $this->report_data->total_tax ) - max( 0, $this->report_data->total_shipping_tax ) - max( 0, $this->report_data->total_stripe_fees ), 2 );`
should be
`$this->report_data->net_sales = wc_format_decimal( $this->report_data->total_sales - $this->report_data->total_shipping - max( 0, $this->report_data->total_tax ) - max( 0, $this->report_data->total_shipping_tax ) - max( 0, $this->report_data->total_stripe_fees ), 2 );`

https://github.com/rvola/woo-stripe-fee-in-report/blob/e3670edb3b5697be9b822540817d28b16cab6dc9/includes/class-report.php#L140

**Comment by rvola** [comment]
Good job ! @manwithpowers

**Comment by manwithpowers** [comment]
Thanks, and thanks for the fix!
